import type { Park } from './disneyFoodTypes';

export const magicKingdom: Park = {
  name: 'Magic Kingdom',
  lands: [
    {
      name: 'Adventureland',
      locations: [
        {
          name: 'Jungle Navigation Co. LTD Skipper Canteen',
          type: 'avoid',
          description: 'Table Service',
          foodItems: [],
        },
        {
          name: 'The Beak and Barrel',
          type: 'avoid',
          description: 'No Plan',
          foodItems: [],
        },
        {
          name: 'Tortuga Tavern',
          type: 'quick-service',
          description: 'American Classics',
          foodItems: [
            { name: 'Lemonade slushy', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
          ],
        },
        {
          name: 'Aloha Isle',
          type: 'snack',
          foodItems: [
            { name: 'Pineapple upside-down cake', type: 'snack' },
            { name: 'Pineapple Dole Whip', type: 'snack' },
            { name: 'Pineapple juice float', type: 'snack' },
            { name: 'Coconut cup', type: 'snack' },
            { name: 'Pineapple juice', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
          ],
        },
        {
          name: 'Egg Roll Snack Cart',
          type: 'snack',
          foodItems: [
            { name: 'All bottled drinks', type: 'snack' },
          ],
        },
        {
          name: 'Sunshine Tree Terrace',
          type: 'snack',
          foodItems: [
            { name: 'Cold brew with sweet cream', type: 'snack' },
            { name: 'Ice cream float', type: 'snack' },
            { name: 'Other floats', type: 'snack' },
            { name: 'Soft serves', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
          ],
        },
      ],
    },
    {
      name: 'Fantasyland',
      locations: [
        {
          name: 'Cinderella’s Royal Table',
          type: 'avoid',
          description: 'Table Service',
          foodItems: [],
        },
        {
          name: 'Be Our Guest',
          type: 'avoid',
          description: 'Table Service',
          foodItems: [],
        },
        {
          name: 'Pinocchio Village Haus',
          type: 'quick-service',
          description: 'Flatbreads, Salads, Chicken',
          foodItems: [
            { name: 'Greek yogurt', type: 'snack' },
            { name: 'Fries', type: 'snack' },
            { name: 'Tomato soup', type: 'snack' },
            { name: 'Breadsticks', type: 'snack' },
            { name: 'Side Caesar', type: 'snack' },
            { name: 'Tea', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Hot/Cold Chocolate', type: 'snack' },
            { name: 'Orange juice', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Blue Raspberry Slush', type: 'snack' },
          ],
        },
        {
          name: 'The Friar’s Nook',
          type: 'quick-service',
          description: 'Breakfast, Hot Dogs',
          foodItems: [
            { name: 'Flavoured lemonades', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Tea', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Hot/Cold Chocolate', type: 'snack' },
            { name: 'Orange juice', type: 'snack' },
          ],
        },
        {
          name: 'Storybook Treats',
          type: 'snack',
          foodItems: [
            { name: 'Soft serve', type: 'snack' },
            { name: 'Floats', type: 'snack' },
            { name: 'Hot fudge sundae', type: 'snack' },
            { name: 'Various sundaes', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Hot Chocolate', type: 'snack' },
          ],
        },
        {
          name: 'Gaston’s Tavern',
          type: 'snack',
          foodItems: [
            { name: 'Crème brûlée croissant', type: 'snack' },
            { name: 'Warm cinnamon roll', type: 'snack' },
            { name: 'Cupcake', type: 'snack' },
            { name: 'Tea', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Hot/Cold Chocolate', type: 'snack' },
            { name: 'Orange juice', type: 'snack' },
            { name: 'Apple juice', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
          ],
        },
        {
          name: 'Prince Eric’s Village Market',
          type: 'snack',
          foodItems: [
            { name: 'Pickle', type: 'snack' },
            { name: 'Grapes', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Bottled beverages', type: 'snack' },
            { name: 'Slushies', type: 'snack' },
          ],
        },
        {
          name: 'Cheshire Café',
          type: 'snack',
          foodItems: [
            { name: 'Cheshire Cat Tail', type: 'snack' },
            { name: 'Pretzel', type: 'snack' },
            { name: 'Cupcake', type: 'snack' },
            { name: 'Orange juice', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Tea', type: 'snack' },
            { name: 'Monster Energy', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fruity tea slushies', type: 'snack' },
          ],
        },
      ],
    },
    {
      name: 'Frontierland',
      locations: [
        {
          name: 'Diamond Horseshoe',
          type: 'avoid',
          description: 'Table Service',
          foodItems: [],
        },
        {
          name: 'Golden Oak Outpost',
          type: 'quick-service',
          description: 'Breakfast, Beignets, Chicken',
          foodItems: [
            { name: 'Beignets', type: 'snack' },
            { name: 'Sweet potato fries', type: 'snack' },
            { name: 'Lavender drinks', type: 'snack' },
            { name: 'Orange juice', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Milk', type: 'snack' },
          ],
        },
        {
          name: 'Pecos Bill Tall Tale Inn and Café',
          type: 'quick-service',
          description: 'Burgers, Fries, Nachos, Rice Bowls, Salads',
          foodItems: [
            { name: 'Sweet corn mousse', type: 'snack' },
            { name: 'Mini churros', type: 'snack' },
            { name: 'Guacamole', type: 'snack' },
            { name: 'Pinto beans', type: 'snack' },
            { name: 'Cilantro-Lime rice', type: 'snack' },
            { name: 'Chips and queso', type: 'snack' },
            { name: 'Tea', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Hot Chocolate', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Strawberry limeade slush', type: 'snack' },
          ],
        },
        {
          name: 'Westward Ho',
          type: 'snack',
          foodItems: [
            { name: 'Tea', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Slushies', type: 'snack' },
            { name: 'Orange juice (Breakfast only)', type: 'snack' },
            { name: 'Jalapeño poppers (Lunch only)', type: 'snack' },
            { name: 'Crisps (Lunch only)', type: 'snack' },
          ],
        },
        {
          name: 'Frontierland Churro Cart',
          type: 'snack',
          foodItems: [
            { name: 'Churro', type: 'snack' },
            { name: 'Pretzels', type: 'snack' },
            { name: 'Bottled beverages', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
          ],
        },
      ],
    },
    {
      name: 'Liberty Square',
      locations: [
        {
          name: 'Liberty Tree Tavern',
          type: 'avoid',
          description: 'Table Service',
          foodItems: [],
        },
        {
          name: 'Sleepy Hollow',
          type: 'quick-service',
          description: 'Waffles, Funnel Cakes',
          foodItems: [
            { name: 'Funnel cakes', type: 'snack' },
            { name: 'Waffles', type: 'snack' },
            { name: 'Crisps', type: 'snack' },
            { name: 'Banana', type: 'snack' },
            { name: 'Berries', type: 'snack' },
            { name: 'Nutella style spread', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Tea', type: 'snack' },
            { name: 'Hot/Cold Chocolate', type: 'snack' },
            { name: 'Whole milk', type: 'snack' },
            { name: 'Orange juice', type: 'snack' },
            { name: 'Apple juice', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
          ],
        },
        {
          name: 'Columbia Harbour House',
          type: 'quick-service',
          description: 'New England Style Food',
          foodItems: [
            { name: 'Greek yogurt', type: 'snack' },
            { name: 'Boston cream pie', type: 'snack' },
            { name: 'New England clam chowder', type: 'snack' },
            { name: 'French fries', type: 'snack' },
            { name: 'Rice', type: 'snack' },
            { name: 'Green beans', type: 'snack' },
            { name: 'Hush puppies', type: 'snack' },
            { name: 'Tea', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Hot/Cold Chocolate', type: 'snack' },
            { name: 'Orange juice', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Lemonade slushy', type: 'snack' },
          ],
        },
        {
          name: 'Liberty Square Market',
          type: 'snack',
          foodItems: [
            { name: 'Mickey pretzel', type: 'snack' },
            { name: 'Mandarins x3', type: 'snack' },
            { name: 'Crisps', type: 'snack' },
            { name: 'Cookie', type: 'snack' },
            { name: 'Whole fruits', type: 'snack' },
            { name: 'Babybel', type: 'snack' },
            { name: 'Pickle', type: 'snack' },
            { name: 'Bottled beverages', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Slushies', type: 'snack' },
            { name: 'Powerade', type: 'snack' },
            { name: 'Apple juice', type: 'snack' },
            { name: 'Sweet tea', type: 'snack' },
          ],
        },
      ],
    },
    {
      name: 'Main Street U.S.A.',
      locations: [
        {
          name: 'Tony’s Town Square Restaurant',
          type: 'avoid',
          description: 'Table Service',
          foodItems: [],
        },
        {
          name: 'The Plaza Restaurant',
          type: 'avoid',
          description: 'Table Service',
          foodItems: [],
        },
        {
          name: 'The Crystal Palace',
          type: 'avoid',
          description: 'Table Service',
          foodItems: [],
        },
        {
          name: 'Casey’s Corner',
          type: 'quick-service',
          description: 'Hot Dogs, Loaded Fries',
          foodItems: [
            { name: 'Cheese sauce', type: 'snack' },
            { name: 'French fries', type: 'snack' },
            { name: 'Chili', type: 'snack' },
            { name: 'Mandarins x3', type: 'snack' },
            { name: 'Brownie', type: 'snack' },
            { name: 'Mint Julep Lemonade', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Hot/Cold Chocolate', type: 'snack' },
            { name: 'Apple juice', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
          ],
        },
        {
          name: 'Main Street Bakery',
          type: 'quick-service',
          description: 'Starbucks',
          foodItems: [
            { name: 'Most Starbucks drinks', type: 'snack' },
            { name: 'Most Starbucks sweet treats', type: 'snack' },
          ],
        },
        {
          name: 'Plaza Ice Cream Parlour',
          type: 'snack',
          foodItems: [
            { name: 'Milkshakes', type: 'snack' },
            { name: 'Double ice cream cone', type: 'snack' },
            { name: 'Sundaes', type: 'snack' },
            { name: 'Floats', type: 'snack' },
            { name: 'Ice cream sandwich', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Bottled beverages', type: 'snack' },
          ],
        },
      ],
    },
    {
      name: 'Tomorrowland',
      locations: [
        {
          name: 'Cosmic Ray’s Starlight Café',
          type: 'quick-service',
          description: 'Burgers, Fries, Salads',
          foodItems: [
            { name: 'Passion fruit mandarin tart', type: 'snack' },
            { name: 'French fries', type: 'snack' },
            { name: 'Mandarin', type: 'snack' },
            { name: 'Garlic truffle parmesan fries', type: 'snack' },
            { name: 'Tea', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Hot/Cold Chocolate', type: 'snack' },
            { name: 'Orange juice', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Slushies', type: 'snack' },
          ],
        },
        {
          name: 'The Lunching Pad',
          type: 'quick-service',
          description: 'Breakfast, Pretzels',
          foodItems: [
            { name: 'Sticky bubble bread', type: 'snack' },
            { name: 'Cream cheese warm stuffed pretzel', type: 'snack' },
            { name: 'Mickey pretzel', type: 'snack' },
            { name: 'Cheese sauce', type: 'snack' },
            { name: 'Monster energy', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Slushies', type: 'snack' },
            { name: 'Coffee (Breakfast only)', type: 'snack' },
            { name: 'Orange juice (Breakfast only)', type: 'snack' },
          ],
        },
        {
          name: 'AstroFizz',
          type: 'snack',
          foodItems: [
            { name: 'Frozen lemonade cup', type: 'snack' },
            { name: 'Popcorn', type: 'snack' },
            { name: 'Cotton candy', type: 'snack' },
            { name: 'Cinnamon-glazed nuts', type: 'snack' },
            { name: 'Cherry cola churro', type: 'snack' },
            { name: 'Ice cream bar/sandwich', type: 'snack' },
            { name: 'Strawberry ice lolly', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Slushies', type: 'snack' },
          ],
        },
        {
          name: 'Auntie Gravity’s Galactic Goodies',
          type: 'snack',
          foodItems: [
            { name: 'Churro', type: 'snack' },
            { name: 'Soft serve', type: 'snack' },
            { name: 'Floats', type: 'snack' },
            { name: 'Brownie sundae', type: 'snack' },
            { name: 'Shakes', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
          ],
        },
        {
          name: 'Tomorrowland Terrace Restaurant',
          type: 'snack',
          foodItems: [
            { name: 'Greek yogurt', type: 'snack' },
            { name: 'Ice cream', type: 'snack' },
            { name: 'Choc chip lava cookie', type: 'snack' },
            { name: 'French fries', type: 'snack' },
            { name: 'Mandarin x3', type: 'snack' },
            { name: 'Side salad', type: 'snack' },
            { name: 'Hushpuppies', type: 'snack' },
            { name: 'Tea', type: 'snack' },
            { name: 'Coffee', type: 'snack' },
            { name: 'Hot/Cold Chocolate', type: 'snack' },
            { name: 'Orange juice', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
          ],
        },
        {
          name: 'Energy Bytes',
          type: 'snack',
          foodItems: [
            { name: 'Doughnut holes', type: 'snack' },
            { name: 'Watermelon cucumber pineapple cup', type: 'snack' },
            { name: 'Monster energy', type: 'snack' },
            { name: 'Cold brew', type: 'snack' },
            { name: 'Bottled water', type: 'snack' },
            { name: 'Fountain beverages', type: 'snack' },
            { name: 'Slushies', type: 'snack' },
          ],
        },
        {
          name: 'Revive (Joffrey’s)',
          type: 'snack',
          foodItems: [
            { name: 'Everything but the Mocha Espresso Cookie', type: 'snack' },
          ],
        },
      ],
    },
    {
      name: 'Transportation & Ticket Centre',
      locations: [
        {
          name: 'Joffrey’s Coffee Company',
          type: 'snack',
          foodItems: [
            { name: 'Every single menu item', type: 'snack' },
          ],
        },
      ],
    },
  ],
};
